version: '3.4'
services:
  pages-backend:
    build:
      context: ./src/
      args:
        SERVICE_PORT: ${SERVICE_PORT}
    image: "${DOCKER_REGISTRY}wikitolearn/pages-backend:${DOCKER_IMAGE_PAGES_BACKEND_TAG}"
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      MONGO_HOST: ${MONGO_HOST}
